import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import prettier from 'prettier';
import {
  businessDocs,
  componentDocs,
  configProviderDoc,
  renderComponentDoc,
  renderStandaloneDoc,
} from './docs-generator.mjs';

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const specDir = path.join(rootDir, 'ui-spec');

const isCheck = process.argv.includes('--check');
const generatedFiles = new Map();
const lowConfidence = [];

const fileHeader = `// This file is generated by pnpm spec:sync. Do not edit manually.\n`;

const specPath = (...segments) => path.join(specDir, ...segments);

const readSpec = (...segments) => {
  const file = specPath(...segments);
  return existsSync(file) ? readFileSync(file, 'utf8') : '';
};

const walk = (dir) => {
  if (!existsSync(dir)) return [];

  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const entryPath = path.join(dir, entry.name);
    return entry.isDirectory() ? walk(entryPath) : [entryPath];
  });
};

const unique = (values) => [...new Set(values)];

const matchAll = (source, pattern, mapper = (match) => match[0]) =>
  [...source.matchAll(pattern)].map(mapper);

const firstMatch = (source, pattern, fallback = '') =>
  source.match(pattern)?.[1]?.trim() ?? fallback;

const normalizeHex = (value) => value.toUpperCase();

const parsePx = (value, fallback = 0) => {
  const parsed = Number.parseInt(String(value).replace(/`/g, ''), 10);
  return Number.isFinite(parsed) ? parsed : fallback;
};

const normalizeShadow = (value) => value.replace(/\s+/g, ' ').trim();

const toTs = (value) => JSON.stringify(value, null, 2).replace(/"([a-zA-Z_$][\w$]*)":/g, '$1:');

const parserByExtension = {
  '.css': 'css',
  '.md': 'markdown',
  '.ts': 'typescript',
};

const formatGeneratedContent = async (relativePath, content) => {
  const parser = parserByExtension[path.extname(relativePath)];
  if (!parser) return content;
  const filepath = path.join(rootDir, relativePath);
  const config = (await prettier.resolveConfig(filepath)) ?? {};
  return prettier.format(content, { ...config, filepath, parser });
};

const addFile = async (relativePath, content) => {
  generatedFiles.set(
    path.join(rootDir, relativePath),
    await formatGeneratedContent(relativePath, content),
  );
};

const expectSpec = (label, content) => {
  if (!content) lowConfidence.push(`${label}: 未找到新版规范文件。`);
};

const globalSpec = {
  color: readSpec('全局规范', 'Color.style.md'),
  container: readSpec('全局规范', 'Container.style.md'),
  space: readSpec('全局规范', 'AntdSpace.md'),
  typography: readSpec('全局规范', 'Typography.style.md'),
  layout: readSpec('全局规范', 'AntdLayout.md'),
  imageRatio: readSpec('全局规范', 'ImageRatio.style.md'),
  button: readSpec('全局规范', 'Button.style.md'),
};

Object.entries(globalSpec).forEach(([name, content]) => expectSpec(`全局规范/${name}`, content));

const componentSpec = {
  input: readSpec('数据录入', 'Input.dev.md'),
  select: readSpec('数据录入', 'Select.dev.md'),
  datePicker: readSpec('数据录入', 'DatePicker.dev.md'),
  table: readSpec('样式规范', 'Table  表格样式.md'),
  modal: readSpec('反馈', 'AntdModal.md'),
  drawer: readSpec('反馈', 'AntdDrawer.md'),
  alert: readSpec('反馈', 'AntdAlert.md'),
  pagination: readSpec('导航组件', 'pagination-Style-Spec.md'),
  tabs: readSpec('导航组件', 'tabs-Style-Spec.md'),
  steps: readSpec('导航组件', 'steps-Style-Spec.md'),
};

const allSpecFiles = walk(specDir);
const newSpecFiles = allSpecFiles
  .filter((file) => file.endsWith('.md'))
  .map((file) => path.relative(rootDir, file).replaceAll(path.sep, '/'));

const colorValue = (name, fallback) =>
  firstMatch(
    globalSpec.color,
    new RegExp(`-\\s*${name}\\s*:\\s*(#[0-9a-fA-F]{6}|rgba\\([^)]+\\))`),
    fallback,
  );

const brandEntries = matchAll(globalSpec.color, /-\s*brand-(\d+)\s*:\s*(#[0-9a-fA-F]{6})/g, (m) => [
  Number(m[1]),
  normalizeHex(m[2]),
]);

const dataColors = matchAll(
  globalSpec.color,
  /-\s*data-\d+\s*:\s*(#[0-9a-fA-F]{6}|rgba\([^)]+\))/g,
  (m) => (m[1].startsWith('#') ? normalizeHex(m[1]) : m[1]),
);

const gradientColors = matchAll(
  globalSpec.color,
  /-\s*grad-[\w-]+\s*:\s*(linear-gradient\([^)]+\))/g,
  (m) => m[1].replace(/,\s*/g, ', '),
);

const boxShadows = Object.fromEntries(
  matchAll(globalSpec.container, /-\s*(hover|default|modal|tooltip)\s*:\s*([^\n]+)/g, (m) => [
    m[1],
    normalizeShadow(m[2]),
  ]),
);

const radii = Object.fromEntries(
  matchAll(globalSpec.container, /-\s*r-(\d+)\s*:\s*(\d+)px/g, (m) => [`r${m[1]}`, Number(m[2])]),
);

const spacingValues = unique(
  matchAll(globalSpec.space, /`(\d+)px`/g, (m) => Number(m[1])).filter(
    (value) => value > 0 && value <= 32,
  ),
).sort((a, b) => a - b);

const layoutTokens = Object.fromEntries(
  matchAll(globalSpec.layout, /\|\s*`(--[a-z0-9-]+)`\s*\|\s*`([^`]+)`/gi, (m) => [m[1], m[2]]),
);

const ratios = unique(
  matchAll(globalSpec.imageRatio, /aspect-ratio:\s*(\d+\s*\/\s*\d+)/g, (m) =>
    m[1].replace(/\s+/g, ' '),
  ),
);

const fontFamily = firstMatch(globalSpec.typography, /font-family:\s*([^;]+);/s);
const typeScale = matchAll(
  globalSpec.typography,
  /-\s*(\d+)px\s*\/\s*(\d+)px\s*—\s*([^（\n]+)(?:（([^）]+)）)?/g,
  (m) => ({
    fontSize: Number(m[1]),
    lineHeight: Number(m[2]) / Number(m[1]),
    label: m[3].trim(),
    fontWeight: m[4]?.includes('500') ? 500 : 400,
  }),
);

const buttonHeight = parsePx(firstMatch(globalSpec.button, /`default`\s*(\d+)px/, '32'), 32);
const buttonSmallHeight = parsePx(firstMatch(globalSpec.button, /`small`\s*(\d+)px/, '24'), 24);
const buttonRadius = parsePx(firstMatch(globalSpec.button, /圆角：(\d+)px/, '2'), 2);

const inputDefaultHeight = parsePx(
  firstMatch(componentSpec.input, /\|\s*默认\s*\|\s*`(\d+)px`/, '32'),
  32,
);
const inputLargeHeight = parsePx(
  firstMatch(componentSpec.input, /\|\s*大尺寸\s*\|\s*`(\d+)px`/, '40'),
  40,
);
const tableHeaderHeight = parsePx(
  firstMatch(componentSpec.table, /\|\s*高度\s*\|\s*`(\d+)px`/, '34'),
  34,
);
const tableRowHeight = parsePx(
  firstMatch(componentSpec.table, /\|\s*行高度\s*\|\s*`(\d+)px`/, '34'),
  34,
);

const tokens = {
  color: {
    brand: Object.fromEntries(brandEntries),
    text: {
      primary: colorValue('text-primary', 'rgba(0,0,0,0.85)'),
      secondary: colorValue('text-secondary', 'rgba(0,0,0,0.65)'),
      tertiary: colorValue('text-placeholder', 'rgba(0,0,0,0.45)'),
      placeholder: colorValue('text-placeholder', 'rgba(0,0,0,0.45)'),
      disabled: colorValue('text-disabled', 'rgba(0,0,0,0.25)'),
      inverse: 'rgba(255,255,255,1)',
      inverseSecondary: 'rgba(255,255,255,0.65)',
    },
    border: {
      base: colorValue('line-divider', 'rgba(0,0,0,0.15)'),
      strong: colorValue('border-default', 'rgba(0,0,0,0.25)'),
      subtle: 'rgba(0,0,0,0.12)',
      defaultSolid: '#D9D9D9',
    },
    fill: {
      white: colorValue('bg-white', '#FFFFFF'),
      background: colorValue('bg-grey', '#F4F6F8'),
      layout: colorValue('page-bg', '#E9EBF3'),
      tableHeader: colorValue('table-head-bg', '#F1F2F7'),
      tableHover: '#FAFAFA',
      overlay: colorValue('overlay-mask', 'rgba(0,0,0,0.30)'),
      tooltip: 'rgba(0,0,0,0.75)',
    },
    functional: {
      success: colorValue('success', '#00C078'),
      error: colorValue('error', '#FF4D4F'),
      warning: colorValue('warning', '#FFA000'),
      info: colorValue('info/link', '#1874FF'),
    },
    data: dataColors,
    gradient: gradientColors,
  },
  radius: {
    xs: radii.r2 ?? 2,
    sm: radii.r2 ?? 2,
    md: radii.r4 ?? 4,
    lg: radii.r8 ?? 8,
    round: radii.r100 ?? 100,
  },
  shadow: {
    hover: boxShadows.hover ?? '',
    default: boxShadows.default ?? '',
    modal: boxShadows.modal ?? '',
    tooltip: boxShadows.tooltip ?? '',
  },
  space: {
    xxs: spacingValues[0] ?? 4,
    xs: spacingValues[1] ?? 8,
    sm: spacingValues[2] ?? 12,
    md: spacingValues[3] ?? 16,
    lg: spacingValues[4] ?? 20,
    xl: spacingValues[5] ?? 24,
    xxl: spacingValues[6] ?? 32,
    gridColumns: 12,
    gridGutter: parsePx(firstMatch(globalSpec.space, /水槽\s*Gutter\s*\|\s*`(\d+)px`/, '20'), 20),
  },
  typography: {
    fontFamily:
      fontFamily ??
      '-apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Helvetica, Arial, sans-serif',
    scale: typeScale,
    body: {
      fontSize: 14,
      lineHeight: 22 / 14,
      fontWeight: 400,
    },
    title: {
      fontSize: 20,
      lineHeight: 28 / 20,
      fontWeight: 500,
    },
  },
  layout: {
    headerHeight: parsePx(layoutTokens['--layout-header-height'], 64),
    siderExpandedWidth: parsePx(layoutTokens['--layout-sider-expanded-width'], 208),
    siderCollapsedWidth: parsePx(layoutTokens['--layout-sider-collapsed-width'], 48),
    contentPadding: `${parsePx(layoutTokens['--layout-content-padding-top'], 20)}px ${parsePx(
      layoutTokens['--layout-content-padding-right'],
      16,
    )}px ${parsePx(layoutTokens['--layout-content-padding-bottom'], 20)}px ${parsePx(
      layoutTokens['--layout-content-padding-left'],
      16,
    )}px`,
    pageMarginXl: parsePx(layoutTokens['--page-margin-xl'], 261),
    pageMarginLg: parsePx(layoutTokens['--page-margin-lg'], 120),
    pageMarginBase: parsePx(layoutTokens['--page-margin-base'], 24),
    subNavHeight: parsePx(layoutTokens['--sub-nav-bar-height'], 48),
    tertiaryNavHeight: parsePx(layoutTokens['--tertiary-bar-height'], 40),
    globalBarBg: layoutTokens['--global-bar-bg'] ?? '#090a15',
    sidebarSelectedBg: layoutTokens['--brand-sidebar-selected-bg'] ?? '#FFFCF0',
    tabsActive: layoutTokens['--brand-tabs-active'] ?? '#9B7235',
    tabsFill: layoutTokens['--brand-tabs-fill'] ?? '#C5A267',
  },
  component: {
    button: {
      height: buttonHeight,
      smallHeight: buttonSmallHeight,
      borderRadius: buttonRadius,
      paddingInline: 16,
      smallPaddingInline: 8,
      iconSize: 16,
      gap: 8,
      groupGap: 12,
    },
    input: {
      height: inputDefaultHeight,
      largeHeight: inputLargeHeight,
      paddingInline: 12,
      borderRadius: 2,
      iconSize: 16,
      addonPaddingInline: 16,
    },
    table: {
      headerHeight: tableHeaderHeight,
      rowHeight: tableRowHeight,
      cellPaddingInline: 16,
      checkboxColumnWidth: 48,
    },
  },
  imageRatio: {
    square: ratios[0] ?? '1 / 1',
    classic: ratios[1] ?? '4 / 3',
    golden: ratios[2] ?? '3 / 2',
    widescreen: ratios[3] ?? '16 / 9',
    ultraWide: ratios[4] ?? '2 / 1',
  },
};

const themeTokenDir = path.join(rootDir, 'src', 'theme', 'tokens');
const readThemeToken = (file) => readFileSync(path.join(themeTokenDir, file), 'utf8');

const themeSource = {
  primitive: readThemeToken('primitive-tokens.ts'),
  semantic: readThemeToken('semantic-tokens.ts'),
  antd: readThemeToken('antd-tokens.ts'),
  antdComponent: readThemeToken('antd-component-tokens.ts'),
  wplusComponent: readThemeToken('wplus-component-tokens.ts'),
};

const themeSourceText = Object.values(themeSource).join('\n');
const rawConstValues = Object.fromEntries(
  matchAll(themeSourceText, /export const ([A-Z][A-Z0-9_]*)\s*=\s*([^;\n]+);/g, (m) => [
    m[1],
    m[2].trim(),
  ]),
);

const themeConstValues = {};
const resolveThemeValue = (value) => {
  const normalized = String(value).trim();
  if (/^'.*'$/.test(normalized)) return normalized.slice(1, -1);
  if (/^\d+(?:\.\d+)?$/.test(normalized)) return Number(normalized);
  return themeConstValues[normalized] ?? rawConstValues[normalized] ?? normalized;
};

for (let index = 0; index < 4; index += 1) {
  for (const [name, value] of Object.entries(rawConstValues)) {
    themeConstValues[name] = resolveThemeValue(value);
  }
}

const blockContent = (source, name) =>
  firstMatch(source, new RegExp(`export const ${name}[^=]*=\\s*([\\s\\S]*?)\\s*] as const;`));

const sourceBrandEntries = matchAll(
  themeSource.primitive,
  /export const BRAND_(\d+)\s*=\s*'([^']+)'/g,
  (m) => [Number(m[1]), m[2]],
).sort(([a], [b]) => a - b);

const sourceDataColors = matchAll(blockContent(themeSource.primitive, 'DATA_COLORS'), /'([^']+)'/g, (m) => m[1]);
const sourceGradientEntries = matchAll(
  firstMatch(themeSource.primitive, /export const GRADIENTS\s*=\s*({[\s\S]*?}) as const;/),
  /(\w+):\s*'([^']+)'/g,
  (m) => [m[1], m[2]],
);
const sourceRadiusEntries = matchAll(
  blockContent(themeSource.primitive, 'RADIUS_TOKENS'),
  /key:\s*'([^']+)'[\s\S]*?radius:\s*'([^']+)'/g,
  (m) => [m[1], m[2]],
);
const sourceShadowEntries = matchAll(
  blockContent(themeSource.primitive, 'SHADOW_TOKENS'),
  /key:\s*'([^']+)'[\s\S]*?boxShadow:\s*([^,\n]+)/g,
  (m) => [m[1], resolveThemeValue(m[2])],
);
const sourceSpacingEntries = matchAll(
  firstMatch(themeSource.primitive, /export const wplusSpacing\s*=\s*({[\s\S]*?}) as const;/),
  /(\w+):\s*(\d+)/g,
  (m) => [m[1], Number(m[2])],
);
const sourceTypographyEntries = matchAll(
  blockContent(themeSource.primitive, 'TYPOGRAPHY_TOKENS'),
  /key:\s*'([^']+)'[\s\S]*?label:\s*'([^']+)'[\s\S]*?fontSize:\s*([^,\n]+)[\s\S]*?lineHeight:\s*([^,\n]+)[\s\S]*?fontWeight:\s*([^,\n]+)/g,
  (m) => [
    m[1],
    {
      label: m[2],
      fontSize: resolveThemeValue(m[3]),
      lineHeight: resolveThemeValue(m[4]),
      fontWeight: resolveThemeValue(m[5]),
    },
  ],
);
const sourceAntdTokenEntries = matchAll(
  firstMatch(themeSource.antd, /export const antdTokens\s*=\s*({[\s\S]*?})\s*as const;/),
  /^\s{4}([a-zA-Z]\w+):\s*([^,\n]+)/gm,
  (m) => [m[1], resolveThemeValue(m[2])],
);

const sourceTheme = {
  brand: Object.fromEntries(sourceBrandEntries),
  dataColors: sourceDataColors,
  gradients: Object.fromEntries(sourceGradientEntries),
  radius: Object.fromEntries(sourceRadiusEntries),
  shadows: Object.fromEntries(sourceShadowEntries),
  spacing: Object.fromEntries(sourceSpacingEntries),
  typography: Object.fromEntries(sourceTypographyEntries),
  antdTokens: Object.fromEntries(sourceAntdTokenEntries),
  componentTokenCount: matchAll(themeSource.antdComponent, /^\s{4}[A-Z]\w+:\s*{/gm).length,
  wplusComponentTokenCount: matchAll(themeSource.wplusComponent, /^\s{2}[a-zA-Z]\w+:\s*{/gm).length,
};

const componentNames = [
  'Button',
  'Form',
  'Table',
  'Input',
  'InputNumber',
  'Select',
  'DatePicker',
  'TimePicker',
  'Cascader',
  'TreeSelect',
  'Checkbox',
  'Radio',
  'Switch',
  'Slider',
  'Upload',
  'Drawer',
  'Alert',
  'Popconfirm',
  'Progress',
  'Result',
  'Skeleton',
  'Spin',
  'Card',
  'Layout',
  'Pagination',
  'Tabs',
  'Steps',
  'Breadcrumb',
  'Anchor',
  'BackTop',
  'Avatar',
  'Badge',
  'Carousel',
  'Collapse',
  'Descriptions',
  'Image',
  'List',
  'Popover',
  'Statistic',
  'Tag',
  'Tooltip',
  'Tour',
];

const componentTypeNames = [
  'ButtonProps',
  'FormProps',
  'TableProps',
  'InputProps',
  'InputNumberProps',
  'SelectProps',
  'DatePickerProps',
  'TimePickerProps',
  'CascaderProps',
  'TreeSelectProps',
  'CheckboxProps',
  'RadioProps',
  'SwitchProps',
  'SliderSingleProps',
  'UploadProps',
  'ModalProps',
  'DrawerProps',
  'AlertProps',
  'PopconfirmProps',
  'ProgressProps',
  'ResultProps',
  'SkeletonProps',
  'SpinProps',
  'CardProps',
  'PaginationProps',
  'TabsProps',
  'StepsProps',
  'BreadcrumbProps',
  'AnchorProps',
  'FloatButtonProps',
  'AvatarProps',
  'BadgeProps',
  'CarouselProps',
  'CollapseProps',
  'DescriptionsProps',
  'ImageProps',
  'ListProps',
  'PopoverProps',
  'StatisticProps',
  'TagProps',
  'TooltipProps',
  'TourProps',
];

const toSlug = (name) => name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

const sidebarItem = (title, link) => ({ title, link });
const primaryComponentNames = ['ConfigProvider', 'Button', 'Form', 'Table'];
const componentCategories = ['数据录入', '数据展示', '反馈', '导航'];
const primaryComponentSidebar = {
  title: '基础能力',
  children: primaryComponentNames.map((name) =>
    sidebarItem(
      componentDocs.find((doc) => doc.name === name)?.title ?? name,
      `/components/${toSlug(name)}`,
    ),
  ),
};

const generatedComponentSidebar = componentCategories
  .map((category) => ({
    title: category,
    children: componentDocs
      .filter((doc) => doc.category === category)
      .map((doc) => sidebarItem(doc.title, `/components/${toSlug(doc.name)}`)),
  }))
  .filter((group) => group.children.length);

const ComponentSidebar = [primaryComponentSidebar, ...generatedComponentSidebar];
const BusinessSidebar = [
  {
    title: '业务沉淀',
    children: businessDocs.map((doc) =>
      sidebarItem(doc.title, `/${doc.path.replace(/^docs\//, '').replace(/\.md$/, '')}`),
    ),
  },
];
const GeneratedSidebar = [
  {
    title: '设计规范',
    children: [
      sidebarItem('组件总览', '/generated/components'),
      sidebarItem('设计 Token', '/generated/design-tokens'),
      sidebarItem('解析报告', '/generated/spec-report'),
    ],
  },
];

if (brandEntries.length < 10) lowConfidence.push('Color.style.md: 品牌色少于 10 项。');
if (dataColors.length < 10) lowConfidence.push('Color.style.md: 数据色少于 10 项。');
if (gradientColors.length < 3) lowConfidence.push('Color.style.md: 渐变色少于 3 项。');
if (Object.keys(boxShadows).length < 4) lowConfidence.push('Container.style.md: 投影少于 4 项。');
if (Object.keys(radii).length < 5) lowConfidence.push('Container.style.md: 圆角少于 5 项。');
if (spacingValues.length < 7) lowConfidence.push('AntdSpace.md: 间距体系少于 7 项。');
if (ratios.length < 5) lowConfidence.push('ImageRatio.style.md: 图片比例少于 5 项。');
if (!typeScale.length) lowConfidence.push('Typography.style.md: 未识别字号/行高映射。');

// CSS 变量和组件样式覆盖已迁移至 src/styles/css-variables.css 及各组件 styles.css
// 不再由此脚本自动生成。

await addFile(
  'src/components/generated/index.ts',
  `${fileHeader}export { ${componentNames.join(', ')} } from 'antd';\nexport type { ${componentTypeNames.join(', ')} } from 'antd';\n`,
);

await addFile(
  'dumi.sidebar.ts',
  `${fileHeader}export const ComponentSidebar = ${toTs(ComponentSidebar)};
export const BusinessSidebar = ${toTs(BusinessSidebar)};
export const GeneratedSidebar = ${toTs(GeneratedSidebar)};
`,
);

for (const [index, doc] of componentDocs.entries()) {
  await addFile(`docs/components/${toSlug(doc.name)}.md`, renderComponentDoc(doc, 100 + index));
}

for (const [index, doc] of businessDocs.entries()) {
  await addFile(doc.path, renderStandaloneDoc(doc, 200 + index));
}

await addFile(configProviderDoc.path, renderStandaloneDoc(configProviderDoc, 1));

await addFile(
  'docs/generated/design-tokens.md',
  `---\ntitle: 设计 Token\norder: 100\n---\n\n# 设计 Token\n\n本页由 \`pnpm spec:sync\` 根据新版 \`ui-spec/\` 自动生成。\n\n## 品牌色\n\n| Token | Value |\n| --- | --- |\n${Object.entries(
    tokens.color.brand,
  )
    .map(([key, value]) => `| Brand ${key} | \`${value}\` |`)
    .join('\n')}\n\n## 功能色\n\n| Token | Value |\n| --- | --- |\n${Object.entries(
    tokens.color.functional,
  )
    .map(([key, value]) => `| ${key} | \`${value}\` |`)
    .join('\n')}\n\n## 圆角\n\n| Token | Value |\n| --- | --- |\n${Object.entries(tokens.radius)
    .map(([key, value]) => `| ${key} | \`${value}px\` |`)
    .join(
      '\n',
    )}\n\n## 组件摘要\n\n| Component | Token | Value |\n| --- | --- | --- |\n| Button | height | \`${tokens.component.button.height}px\` |\n| Button | borderRadius | \`${tokens.component.button.borderRadius}px\` |\n| Input | height | \`${tokens.component.input.height}px\` |\n| Input | largeHeight | \`${tokens.component.input.largeHeight}px\` |\n| Table | headerHeight | \`${tokens.component.table.headerHeight}px\` |\n| Table | rowHeight | \`${tokens.component.table.rowHeight}px\` |\n\n## 图片比例\n\n| Token | Value |\n| --- | --- |\n${Object.entries(
    tokens.imageRatio,
  )
    .map(([key, value]) => `| ${key} | \`${value}\` |`)
    .join('\n')}\n`,
);

await addFile(
  'docs/generated/components.md',
  `---\ntitle: 自动生成组件\norder: 110\n---\n\n# 自动生成组件\n\n以下组件由新版 \`ui-spec/\` 的高频 antd 组件规范生成导出清单，API 与 antd 保持一致，并通过 \`ConfigProvider\` 接收企业主题。\n\n| 组件 | 用法 |\n| --- | --- |\n${componentNames.map((name) => `| ${name} | \`import { ${name} } from 'privatebank-design'\` |`).join('\n')}\n`,
);

await addFile(
  'docs/generated/spec-report.md',
  `---\ntitle: 规范解析报告\norder: 120\n---\n\n# 规范解析报告\n\n本页由 \`pnpm spec:sync\` 自动生成，用于检查新版 Markdown 规范解析结果。\n\n## 已识别\n\n- 规范文件：${newSpecFiles.length} 个\n- 品牌色：${brandEntries.length} 项\n- 数据色：${dataColors.length} 项\n- 渐变色：${gradientColors.length} 项\n- 投影：${Object.keys(boxShadows).length} 项\n- 圆角：${Object.keys(radii).length} 项\n- 间距：${spacingValues.length} 项\n- 字体层级：${typeScale.length} 项\n- 图片比例：${ratios.length} 项\n- 自动导出组件：${componentNames.length} 个\n- 独立组件文档：${componentDocs.length + 4} 个\n- CSS 覆盖：Modal、Drawer、Alert、Popconfirm、Popover、Collapse、Descriptions、Tabs、Pagination、Upload 等\n- 业务组件：ErrorBlock、Status、DetailPageHeader、ApprovalProgressSteps\n\n## 低置信度项\n\n${lowConfidence.length ? lowConfidence.map((item) => `- ${item}`).join('\n') : '- 无'}\n\n## 处理原则\n\n- 能稳定映射到 Ant Design v5 token 的规则进入 \`ThemeConfig\`。\n- antd token 无法表达的 DOM 级细节进入生成 CSS 覆盖。\n- 非 antd 直接导出的业务规范通过业务组件承载。\n`,
);

await addFile(
  'docs/theme.md',
  `---\ntitle: 主题定制\norder: 2\n---\n\n# 主题定制\n\n\`privatebank-design\` 通过 \`enterpriseTheme\` 统一维护企业 token，并在包装版 \`ConfigProvider\` 中默认合并。\n\n当前主题已从新版 \`ui-spec/\` 提取以下设计规范：\n\n| 规范目录                                       | 落地方式                               |\n| ---------------------------------------------- | -------------------------------------- |\n| \`全局规范/Color.style.md\`                      | 品牌色、中性色、功能色、数据色、渐变色 |\n| \`全局规范/Container.style.md\`                  | 圆角、阴影、容器边框与背景             |\n| \`全局规范/AntdSpace.md\`                        | 4px 间距体系、12 列栅格、Space 预设    |\n| \`全局规范/Typography.style.md\`                 | 字体族、字号、行高、字重               |\n| \`全局规范/AntdLayout.md\`                       | Header、Sider、内容区、导航尺寸 token  |\n| \`全局规范/ImageRatio.style.md\`                 | 常用图片比例 token 与 CSS 变量         |\n| \`数据录入/\`、\`样式规范/\`、\`反馈/\`、\`导航组件/\` | 可稳定映射的组件级 antd 主题 token     |\n\n## 内置 token\n\n\`\`\`tsx\nimport { Button, ConfigProvider, globalDesignTokens } from 'privatebank-design';\n\nexport default () => (\n  <ConfigProvider>\n    <Button type="primary">{globalDesignTokens.color.brand[7]}</Button>\n  </ConfigProvider>\n);\n\`\`\`\n\n## 覆盖主题\n\n\`\`\`tsx\nimport { Button, ConfigProvider, createEnterpriseTheme } from 'privatebank-design';\n\nconst theme = createEnterpriseTheme({\n  primaryColor: '#0052d9',\n  borderRadius: 6,\n});\n\nexport default () => (\n  <ConfigProvider theme={theme}>\n    <Button type="primary">企业主按钮</Button>\n  </ConfigProvider>\n);\n\`\`\`\n\n组件级细节优先通过 antd token 落地；无法稳定映射的交互、热区和组合布局保留在规范文档中，后续通过包装组件或业务组件沉淀。\n\n## CSS 变量\n\n引入 \`privatebank-design/reset.css\` 后可使用基础 CSS 变量：\n\n\`\`\`css\n.page {\n  background: var(--wplus-color-bg-page);\n  padding: var(--wplus-layout-content-padding);\n}\n\n.cover {\n  aspect-ratio: var(--wplus-image-ratio-widescreen);\n  border-radius: var(--wplus-radius-md);\n}\n\`\`\`\n`,
);

await addFile(
  'docs/generated/design-tokens.md',
  `---
title: 设计 Token
order: 100
---

# 设计 Token

本页由 \`pnpm spec:sync\` 根据 \`src/theme/\` 自动生成。

## 品牌色

| Token | Value |
| --- | --- |
${Object.entries(sourceTheme.brand)
  .map(([key, value]) => `| Brand ${key} | \`${value}\` |`)
  .join('\n')}

## 数据色

| Index | Value |
| --- | --- |
${sourceTheme.dataColors.map((value, index) => `| ${index + 1} | \`${value}\` |`).join('\n')}

## 渐变色

| Token | Value |
| --- | --- |
${Object.entries(sourceTheme.gradients)
  .map(([key, value]) => `| ${key} | \`${value}\` |`)
  .join('\n')}

## 圆角

| Token | Value |
| --- | --- |
${Object.entries(sourceTheme.radius)
  .map(([key, value]) => `| ${key} | \`${value}\` |`)
  .join('\n')}

## 阴影

| Token | Value |
| --- | --- |
${Object.entries(sourceTheme.shadows)
  .map(([key, value]) => `| ${key} | \`${value}\` |`)
  .join('\n')}

## Ant Design 全局 Token

| Token | Value |
| --- | --- |
${Object.entries(sourceTheme.antdTokens)
  .slice(0, 24)
  .map(([key, value]) => `| ${key} | \`${value}\` |`)
  .join('\n')}
`,
);

await addFile(
  'docs/generated/components.md',
  `---
title: 自动生成组件
order: 110
---

# 自动生成组件

以下组件文档由 \`pnpm spec:sync\` 自动生成，示例统一从 \`privatebank-design\` 导入，API 与 Ant Design v5 保持兼容。

| 组件 | 用法 |
| --- | --- |
${componentNames.map((name) => `| ${name} | \`import { ${name} } from 'privatebank-design'\` |`).join('\n')}
`,
);

await addFile(
  'docs/generated/spec-report.md',
  `---
title: 解析报告
order: 120
---

# 解析报告

本页由 \`pnpm spec:sync\` 自动生成，用于检查源码 token 与文档生成结果。

## 已识别

- 主题来源：\`src/theme/\`
- 品牌色：${Object.keys(sourceTheme.brand).length} 项
- 数据色：${sourceTheme.dataColors.length} 项
- 渐变色：${Object.keys(sourceTheme.gradients).length} 项
- 圆角 token：${Object.keys(sourceTheme.radius).length} 项
- 阴影 token：${Object.keys(sourceTheme.shadows).length} 项
- 间距 token：${Object.keys(sourceTheme.spacing).length} 项
- 字体层级：${Object.keys(sourceTheme.typography).length} 项
- antd 全局 token：${Object.keys(sourceTheme.antdTokens).length} 项
- antd 组件 token 分组：${sourceTheme.componentTokenCount} 项
- W+ 组件 token 分组：${sourceTheme.wplusComponentTokenCount} 项
- 自动导出组件：${componentNames.length} 个
- 独立组件文档：${componentDocs.length + businessDocs.length + 1} 个

## 低置信度项

${lowConfidence.length ? lowConfidence.map((item) => `- ${item}`).join('\n') : '- 无'}

## 处理原则

- 文档中的设计 Token 以 \`src/theme/tokens\` 为准。
- antd 可表达的样式进入 \`wplusTheme\`、\`antdTokens\` 和 \`antdComponentTokens\`。
- 复杂布局和业务语义通过包装组件、业务组件和文档示例沉淀。
`,
);

await addFile(
  'docs/theme.md',
  `---
title: 主题定制
order: 2
---

# 主题定制

\`privatebank-design\` 通过 \`wplusTheme\` 统一维护企业主题，并在包装版 \`ConfigProvider\` 中默认合并。

当前主题从 \`src/theme/\` 解析生成，核心来源如下：

| 源码文件 | 落地方式 |
| --- | --- |
| \`src/theme/tokens/primitive-tokens.ts\` | 品牌色、数据色、渐变、圆角、阴影、间距和字体层级 |
| \`src/theme/tokens/semantic-tokens.ts\` | 业务语义色、文字色、背景色、边框色 |
| \`src/theme/tokens/antd-tokens.ts\` | Ant Design 全局 token |
| \`src/theme/tokens/antd-component-tokens.ts\` | Ant Design 组件级 token |
| \`src/theme/tokens/wplus-component-tokens.ts\` | W+ 组件语义 token |

## 内置 token

\`\`\`tsx
import { BRAND_COLORS, Button, ConfigProvider } from 'privatebank-design';

export default () => (
  <ConfigProvider>
    <Button type="primary">{BRAND_COLORS.brand7}</Button>
  </ConfigProvider>
);
\`\`\`

## 覆盖主题

\`\`\`tsx
import { Button, ConfigProvider } from 'privatebank-design';

export default () => (
  <ConfigProvider theme={{ token: { colorPrimary: '#0052d9', borderRadius: 6 } }}>
    <Button type="primary">企业主按钮</Button>
  </ConfigProvider>
);
\`\`\`

## 复用完整主题

\`\`\`tsx
import { Button, ConfigProvider, wplusTheme } from 'privatebank-design';

export default () => (
  <ConfigProvider theme={wplusTheme}>
    <Button type="primary">W+ 主题按钮</Button>
  </ConfigProvider>
);
\`\`\`

## CSS 变量

引入 \`privatebank-design/reset.css\` 后可使用基础 CSS 变量：

\`\`\`css
.page {
  background: var(--wplus-color-bg-page);
  padding: var(--wplus-layout-content-padding);
}

.cover {
  aspect-ratio: var(--wplus-image-ratio-widescreen);
  border-radius: var(--wplus-radius-md);
}
\`\`\`
`,
);

const writeOrCheck = () => {
  let hasDiff = false;

  for (const [file, content] of generatedFiles) {
    const current = existsSync(file) ? readFileSync(file, 'utf8') : null;

    if (current !== content) {
      hasDiff = true;
      if (isCheck) {
        console.error(`Generated file is out of date: ${path.relative(rootDir, file)}`);
      } else {
        mkdirSync(path.dirname(file), { recursive: true });
        writeFileSync(file, content);
      }
    }
  }

  if (isCheck && hasDiff) {
    process.exitCode = 1;
    return;
  }

  console.log(
    isCheck ? 'ui-spec generated files are up to date.' : 'ui-spec generated files synced.',
  );
};

writeOrCheck();
